### ISSUE TITLE
Collecting results fails with Cygwin

### ISSUE THREAD

**Issue by thtrummer** [boostorg/regression#37] opened 2016-02-25 10:09 UTC
The test suite seems to run fine, however, when collecting the results the used path is wrong. It is prepended with the physical location of the folder ("E:/Boost\Develop\boost_root\status"), though it probably should only use the virtual path ("\cygdrive\e\Boost\Develop\") and maybe only forward slashes.

```
[...]
*****Warning - can't open output file: E:/Boost\Develop\boost_root\status\cygdrive\e\Boost\Develop\results\xt~boost~fusion~deque~auto~drop_front.test/gcc-5.3.0/debug/ext/boost/fusion/deque/auto\test_log.xml
*****Warning - can't open output file: E:/Boost\Develop\boost_root\status\cygdrive\e\Boost\Develop\results\xt~boost~fusion~deque~auto~drop_while.test/gcc-5.3.0/debug/ext/boost/fusion/deque/auto\test_log.xml
*****Warning - can't open output file: E:/Boost\Develop\boost_root\status\cygdrive\e\Boost\Develop\results\xt~boost~fusion~deque~auto~group.test/gcc-5.3.0/debug/ext/boost/fusion/deque/auto\test_log.xml
# Collecting test logs into "/cygdrive/e/Boost/Develop/results/timber-cygwin.xml"...
# Reading comments file "/cygdrive/e/Boost/Develop/full-comment.html"...
# Collecting test logs ...
# Walking directory "/cygdrive/e/Boost/Develop/results" ...
#     Processing test log "/cygdrive/e/Boost/Develop/results/boost-build-gcc-5.3.0/test_log.xml"
# Done writing "/cygdrive/e/Boost/Develop/results/timber-cygwin.xml".
# Compressing "/cygdrive/e/Boost/Develop/results/timber-cygwin.xml"...
# Done writing "/cygdrive/e/Boost/Develop/results/timber-cygwin.zip".
# Uploading log archive "/cygdrive/e/Boost/Develop/results/timber-cygwin.zip" to develop
```

**Comment by swatanabe** [comment] 2016-02-26 05:28
AMDG

On 02/25/2016 03:09 AM, Thomas Trummer wrote:

> The test suite seems to run fine, however, when collecting the results the used path is wrong. It is prepended with physical location of the folder ("E:/Boost\Develop\boost_root\status"), though it probably should only use the virtual path ("\cygdrive\e\Boost\Develop\") and maybe only forward slashes.
> 
> ```
> [...]
> *****Warning - can't open output file: E:/Boost\Develop\boost_root\status\cygdrive\e\Boost\Develop\results\xt~boost~fusion~deque~auto~drop_front.test/gcc-5.3.0/debug/ext/boost/fusion/deque/auto\test_log.xml
> 
> ```

  It looks to me like Boost.Filesystem decides that cygwin is
windows and chokes on cygwin paths.

In Christ,
Steven Watanabe

**Comment by mibintc** [comment] 2016-02-26 16:12
On 02/25/2016 03:09 AM, Thomas Trummer wrote:

> The test suite seems to run fine, however, when collecting the results the used path is wrong. It is prepended with physical location of the folder ("E:/Boost\Develop\boost_root\status"), though it probably should only use the virtual path ("\cygdrive\e\Boost\Develop\") and maybe only forward slashes.
> 
> ```
> [...]
> *****Warning - can't open output file: E:/Boost\Develop\boost_root\status\cygdrive\e\Boost\Develop\results\xt~boost~fusion~deque~auto~drop_front.test/gcc-5.3.0/debug/ext/boost/fusion/deque/auto\test_log.xml
> 
> ```

  It looks to me like Boost.Filesystem decides that cygwin is windows and chokes on cygwin paths.

  In Christ,
  Steven Watanabe

I would also like to use Cygwin to report regression testing results with run.py and the Intel compiler. 

I see messages like Thomas reports but there are also failures earlier in the process.

For example, these are some messages in results/bjam.log from the run.py process

```
cmd /S /C call "C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.2.180/windows/bin/iclvars.bat" ia32 vs2015 > nul  "&&" icl @"/cygdrive/d/iusers/mblower/_boost/results/boost/bin.v2/libs/hana/test/test~ext~boost~fusion~deque~auto~unique.test/intel-vc14-win-16.0/debug/threading-multi/ext/boost/fusion/deque/auto/unique.obj.rsp"
```

icl: error #10104: unable to open '/cygdrive/d/iusers/mblower/_boost/results/boost/bin.v2/libs/hana/test/test~ext~boost~fusion~deque~auto~unique.test/intel-vc14-win-16.0/debug/threading-multi/ext/boost/fusion/deque/auto/unique.obj.rsp'

The file unique.obj.rsp exists and it is well formed, but neither the Intel nor cl compiler can open the file. (icl and cl are in my path, if I use either icl @...unique.obj.rsp or cl @...unique.obj.rsp I get the same complaint from both compilers "unable to open...unique.obj.rsp")

However if I modify the invocation like so: ^/cygdrive/d^d:^ then both icl and cl know what to do
$ icl @d:/iusers/mblower/_boost/unique.obj.rsp
unique.cpp
Catastrophic error: cannot open source file "../libs/hana/test/ext/boost/fus ...

compilation aborted for ../libs/hana/test/ext/boost/fusion/deque/auto/unique
 (code 4)

mblower@NHEW202 /cygdrive/d/iusers/mblower/_boost
$ cl @/cygdrive/d/iusers/mblower/_boost/unique.obj.rsp  ## fail same as Intel compiler
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8022 : cannot open '/cygdrive/d/iusers/mblower/_boo ...
mblower@NHEW202 /cygdrive/d/iusers/mblower/_boost
$ cl @d:/iusers/mblower/_boost/unique.obj.rsp  ## success
cl : Command line warning D9002 : ignoring unknown option '/Qwn5'
cl : Command line warning D9002 : ignoring unknown option '/Qwd985'
cl : Command line warning D9002 : ignoring unknown option '-Qoption,c,--arg_

**Comment by swatanabe** [comment] 2016-02-26 16:31
AMDG

On 02/26/2016 09:12 AM, Melanie Blower wrote:

> I would also like to use Cygwin to report regression testing results with run.py and the Intel compiler. 
> 
> I see messages like Thomas reports but there are also failures earlier in the process.
> 
> For example, these are some messages in results/bjam.log from the run.py process
> 
> ```
> cmd /S /C call "C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.2.180/windows/bin/iclvars.bat" ia32 vs2015 > nul  "&&" icl @"/cygdrive/d/iusers/mblower/_boost/results/boost/bin.v2/libs/hana/test/test~ext~boost~fusion~deque~auto~unique.test/intel-vc14-win-16.0/debug/threading-multi/ext/boost/fusion/deque/auto/unique.obj.rsp"
> ```
> 
> icl: error #10104: unable to open '/cygdrive/d/iusers/mblower/_boost/results/boost/bin.v2/libs/hana/test/test~ext~boost~fusion~deque~auto~unique.test/intel-vc14-win-16.0/debug/threading-multi/ext/boost/fusion/deque/auto/unique.obj.rsp'
> 
> The file unique.obj.rsp exists and it is well formed, but neither the Intel nor cl compiler can open the file. (icl and cl are in my path, if I use either icl @...unique.obj.rsp or cl @...unique.obj.rsp I get the same complaint from both compilers "unable to open...unique.obj.rsp")

  This is a separate problem, and it doesn't really make
sense to me.  The .rsp file is created by @($(<[1]:W).rsp:E=...).
Note the :W which is supposed to convert cygwin paths to
windows.

In Christ,
Steven Watanabe

**Comment by mibintc** [comment] 2016-02-26 16:36
> > This is a separate problem, and it doesn't really make
> > sense to me. The .rsp file is created by @($(<[1]:W).rsp:E=...).
> > Note the :W which is supposed to convert cygwin paths to
> > windows.
> > 
> > In Christ,
> > Steven Watanabe

Thank you Steven.  Can you tell me where I can investigate to get to the bottom of this?

**Comment by swatanabe** [comment] 2016-02-26 16:54
AMDG

On 02/26/2016 09:36 AM, Melanie Blower wrote:

> > > This is a separate problem, and it doesn't really make
> > > sense to me. The .rsp file is created by @($(<[1]:W).rsp:E=...).
> > > Note the :W which is supposed to convert cygwin paths to
> > > windows.
> 
> Thank you Steven.  Can you tell me where I can investigate to get to the bottom of this?

The relevant code is src/tools/msvc.jam:408 in actions compile-c-c++.
- This is a problem in Boost.Build.  I usually use
  a command line like b2 -n --with-system --debug-configuration
  from $BOOST_ROOT for debugging.
- What is the value of $(<)?  You can add
  echos in the corresponding rule on line 416.
- Does the :W modifier work correctly in general?
  p = /cygdrive/d/some/path
  ECHO $(p:W) ;
  should print D:\some\path

In Christ,
Steven Watanabe

**Comment by mibintc** [comment] 2016-02-26 19:34
> > The relevant code is src/tools/msvc.jam:408 in actions compile-c-c++.
> > - This is a problem in Boost.Build. I usually use
> >   a command line like b2 -n --with-system --debug-configuration
> >   from $BOOST_ROOT for debugging.
> > - What is the value of $(<)? You can add
> >   echos in the corresponding rule on line 416.
> > - Does the :W modifier work correctly in general?
> >   p = /cygdrive/d/some/path
> >   ECHO $(p:W) ;
> >   should print D:\some\path
> > 
> > In Christ,
> > Steven Watanabe

I can build the boost library from the command line using b2, and Cygwin with the intel toolset (modulo a compilation error or so), but the problem arises in the regression testing from run.py. I can see that the b2 from the console (the test you recommended) is using relative path names to refer to .rsp, and that works fine, but the compiler invocations that ultimately originate from run.py are using full path names starting with /cygdrive/d 

Here's the diff to msvc.jam (run.py did the git from master) -- I guess I goofed on echo $p. hmm the output lines are out-of-order that's interesting.
$ git diff
diff --git a/src/tools/msvc.jam b/src/tools/msvc.jam
index f3561db..5dd27e7 100644
--- a/src/tools/msvc.jam
+++ b/src/tools/msvc.jam
@@ -417,6 +417,10 @@ rule compile-c-c++ ( targets + : sources \* )
 {
     DEPENDS $(<[1]) : [ on $(<[1]) return $(PCH_HEADER) ] ;
     DEPENDS $(<[1]) : [ on $(<[1]) return $(PCH_FILE) ] ;
-    p = /cygdrive/d/iusers/mblower
-    ECHO "notice : p is" $p ;
-    ECHO "notice : p windows is" $(p:W) ;
-    ECHO "notice : less than is" $(<) ;
   PDB_NAME on $(<) = $(<[1]:S=.pdb) ;
   LOCATE on $(<[1]:S=.pdb) = [ on $(<[1]) return $(LOCATE) ] ;
  }

Here's the invocation (tho' in general I would use intel toolset),  ../boost_bb/src/engine/bin.cygwinx86/b2.exe toolset=msvc-14.0 -n --with-system --debug-configuration >& ~/err2.txt

Here's a bit of the output:
notice: [python-cfg]   library path: "/usr/lib/python2.7/config" "/usr/lib"
notice : p windows is /cygdrive/d/iusers/mblower ECHO notice : p is $p
notice : less than is <plibs/config/checks/architecture/bin/msvc-14.0/debug/threading-multi>32.obj
Performing configuration checks

OK so maybe this is the problem. I wanted to run.py using intel toolset everywhere but the toolset wasn't recognized to build the build tools. So I dropped off bjam-toolset and pjl-toolset and just used the default which is gcc on Cygwin
Maybe that's how it's getting confused about how to name the files
I will try again using the msvc toolset

Wanted to use this: but bjam and pjl toolset not recognized, so dropped off these 2 options

# python ./run.py  --toolsets=intel-16.0-vc14 "--bjam-options='-j2'" --runner=intel-win7-master --tag=master  --skip-script-download  --bjam-toolset=intel-16.0-vc14 --pjl-toolset=intel-16.0-vc14

Maybe if I use msvc-14.0 to as bjam-toolset and pjl-toolset it will work

**Comment by swatanabe** [comment] 2016-02-26 19:55
AMDG

On 02/26/2016 12:34 PM, Melanie Blower wrote:

> I can build the boost library from the command line using b2, and Cygwin with the intel toolset (modulo a compilation error or so), but the problem arises in the regression testing from run.py. I can see that the b2 from the console (the test you recommended) is using relative path names to refer to .rsp, and that works fine, but the compiler invocations that ultimately originate from run.py are using full path names starting with /cygdrive/d 

Okay, so what is the exact b2 command that run.py uses?

> Here's the diff to msvc.jam (run.py did the git from master) -- I guess I goofed on echo $p. hmm the output lines are out-of-order that's interesting.
> $ git diff
> diff --git a/src/tools/msvc.jam b/src/tools/msvc.jam
> index f3561db..5dd27e7 100644
> --- a/src/tools/msvc.jam
> +++ b/src/tools/msvc.jam
> @@ -417,6 +417,10 @@ rule compile-c-c++ ( targets + : sources \* )
>  {
>      DEPENDS $(<[1]) : [ on $(<[1]) return $(PCH_HEADER) ] ;
>      DEPENDS $(<[1]) : [ on $(<[1]) return $(PCH_FILE) ] ;
> -    p = /cygdrive/d/iusers/mblower

Missing ';'

> -    ECHO "notice : p is" $p ;
> -    ECHO "notice : p windows is" $(p:W) ;
> -    ECHO "notice : less than is" $(<) ;
>    PDB_NAME on $(<) = $(<[1]:S=.pdb) ;
>    LOCATE on $(<[1]:S=.pdb) = [ on $(<[1]) return $(LOCATE) ] ;
>   }
> 
> Here's the invocation (tho' in general I would use intel toolset),  ../boost_bb/src/engine/bin.cygwinx86/b2.exe toolset=msvc-14.0 -n --with-system --debug-configuration >& ~/err2.txt
> 
> Here's a bit of the output:
> notice: [python-cfg]   library path: "/usr/lib/python2.7/config" "/usr/lib"
> notice : p windows is /cygdrive/d/iusers/mblower ECHO notice : p is $p
> notice : less than is <plibs/config/checks/architecture/bin/msvc-14.0/debug/threading-multi>32.obj
> Performing configuration checks
> 
> OK so maybe this is the problem. I wanted to run.py using intel toolset everywhere but the toolset wasn't recognized to build the build tools. So I dropped off bjam-toolset and pjl-toolset and just used the default which is gcc on Cygwin

That seems like a bug.  I'll see if I can track it down.

> Maybe that's how it's getting confused about how to name the files
> I will try again using the msvc toolset
> 
> Wanted to use this: but bjam and pjl toolset not recognized, so dropped off these 2 options
> 
> # python ./run.py  --toolsets=intel-16.0-vc14 "--bjam-options='-j2'" --runner=intel-win7-master --tag=master  --skip-script-download  --bjam-toolset=intel-16.0-vc14 --pjl-toolset=intel-16.0-vc14
> 
> Maybe if I use msvc-14.0 to as bjam-toolset and pjl-toolset it will work

It probably will, but I'd like to fix this properly.

In Christ,
Steven Watanabe

P.S. For debugging problems with run.py you can use
--libraries=any (or some other small library), so
that it doesn't need to build everything.  --have-source
and --skip-script-download can also help.

**Comment by mibintc** [comment] 2016-02-26 22:28
> > Okay, so what is the exact b2 command that run.py uses?

Here’s the b2 command that I found from using this invocation of run.py. Note: toolset=msvc14.0 wasn’t recognized either. Maybe I’ll try just toolset=msvc
python ./run.py --toolsets=intel-16.0-vc14 --libraries=any --have-source "--bjam -options='-j2'" --runner=intel-win7-master --tag=master --skip-script-download --bjam-toolset=msvc-14.0 --pjl-toolset=msvc-14.0

# Found "b2.exe" source directory "/cygdrive/d/iusers/mblower/_boost_vc/boost_bb/src/engine"

# Building "b2.exe" (./build.sh msvc-14.0)...

###

### Unknown toolset: msvc-14.0

...
    - x86                      : yes
    - symlinks supported       : yes
...found 1054 targets...

# Starting tests ("/cygdrive/d/iusers/mblower/_boost_vc/boost_bb/src/engine/bin.cygwinx86/b2.exe" "-sBOOST_BUILD_PATH=/cygdrive/d/iusers/mblower/_boost_vc:/cygdrive/d/iusers/mblower/_boost_vc/boost_bb/src" "-sBOOST_ROOT=/cygdrive/d/iusers/mblower/_boost_vc/boost_root" "--boost=/cygdrive/d/iusers/mblower/_boost_vc/boost_root" "--boost-root=/cygdrive/d/iusers/mblower/_boost_vc/boost_root" "--boost-build=/cygdrive/d/iusers/mblower/_boost_vc/boost_bb/src" "--debug-configuration" -l300 toolset=intel-16.0-vc14 -d2 preserve-test-targets=off --dump-tests '-j2'"--limit-tests=any" -m64 "--build-dir=/cygdrive/d/iusers/mblower/_boost_vc/results" >>"/cygdrive/d/iusers/mblower/_boost_vc/results/bjam.log" 2>&1)...

# Getting test case results out of "/cygdrive/d/iusers/mblower/_boost_vc/results

/bjam.log"...
boost_root: D:/iusers\mblower_boost_vc\boost_root
locate_root: D:/iusers\mblower_boost_vc\boost_root\status\cygdrive\d\iusers\mblower_boost_vc\results
*****Warning - can't open output file: D:/iusers\mblower_boost_vc\boost_root\status\cygdrive\d\iusers\mblower_boost_vc\results\l-vc14-win-16.0/debug/threading-multi\test_log.xml
Note: same hybrid file names that Thomas reported

> Here's the diff to msvc.jam (run.py did the git from master) -- I guess I goofed on echo $p. hmm the output lines are out-of-order that's interesting.
> $ git diff
> diff --git a/src/tools/msvc.jam b/src/tools/msvc.jam
> index f3561db..5dd27e7 100644
> --- a/src/tools/msvc.jam
> +++ b/src/tools/msvc.jam
> @@ -417,6 +417,10 @@ rule compile-c-c++ ( targets + : sources \* )
> {
> DEPENDS $(<[1]) : [ on $(<[1]) return $(PCH_HEADER) ] ;
> DEPENDS $(<[1]) : [ on $(<[1]) return $(PCH_FILE) ] ;
> - p = /cygdrive/d/iusers/mblower
> 
> > Missing ';'

I fixed the missing semicolon and confirm that :W isn't working as expected. Does '<' look right? What is that supposed to be?  But still not building the build tools with cl, that might still solve the problem.
notice : p is /cygdrive/d/iusers/mblower
notice : p windows is /cygdrive/d/iusers/mblower
notice : less than is <plibs/config/checks/architecture/bin/msvc-14.0/debug/threading-multi>32.obj

Thank you so much for your instruction, Steven, really appreciate it.

**Comment by swatanabe** [comment] 2016-02-26 23:10
AMDG

On 02/26/2016 03:28 PM, Melanie Blower wrote:

> > > Okay, so what is the exact b2 command that run.py uses?
> 
> Here’s the b2 command that I found from using this invocation of run.py. Note: toolset=msvc14.0 wasn’t recognized either. Maybe I’ll try just toolset=msvc
> python ./run.py --toolsets=intel-16.0-vc14 --libraries=any --have-source "--bjam -options='-j2'" --runner=intel-win7-master --tag=master --skip-script-download --bjam-toolset=msvc-14.0 --pjl-toolset=msvc-14.0
> 
> # Found "b2.exe" source directory "/cygdrive/d/iusers/mblower/_boost_vc/boost_bb/src/engine"
> 
> # Building "b2.exe" (./build.sh msvc-14.0)...
> 
> ###
> 
> ### Unknown toolset: msvc-14.0

  It looks like run.py has no way to use msvc (or intel)
to build b2 when you're running under cygwin.

```
echo "### Toolsets supported by this script are:"
echo "###     acc, como, darwin, gcc, intel-darwin, intel-linux,
```

kcc, kylix,"
    echo "###     mipspro, pathscale, pgi, qcc, sun, sunpro, tru64cxx,
vacpp"

It would have to run build.bat instead:

ECHO ### Toolsets supported by this script are: borland, como, gcc,
gcc-nocygwin,
ECHO ###     intel-win32, metrowerks, mingw, msvc, vc7, vc8, vc9, vc10,
vc11, vc12, vc14

  If you want to try using an msvc-built b2, you'll
need to put b2.exe in the directory from which you
use run.py.  run.py should automatically detect and
use a prebuilt b2.  The same goes for process_jam_log.
However, it probably will still fail because there
are too many /cygdrive paths in the b2 command line.

> ...
>     - x86                      : yes
>     - symlinks supported       : yes
> ...found 1054 targets...
> 
> # Starting tests ("/cygdrive/d/iusers/mblower/_boost_vc/boost_bb/src/engine/bin.cygwinx86/b2.exe" "-sBOOST_BUILD_PATH=/cygdrive/d/iusers/mblower/_boost_vc:/cygdrive/d/iusers/mblower/_boost_vc/boost_bb/src" "-sBOOST_ROOT=/cygdrive/d/iusers/mblower/_boost_vc/boost_root" "--boost=/cygdrive/d/iusers/mblower/_boost_vc/boost_root" "--boost-root=/cygdrive/d/iusers/mblower/_boost_vc/boost_root" "--boost-build=/cygdrive/d/iusers/mblower/_boost_vc/boost_bb/src" "--debug-configuration" -l300 toolset=intel-16.0-vc14 -d2 preserve-test-targets=off --dump-tests '-j2'"--limit-tests=any" -m64 "--build-dir=/cygdrive/d/iusers/mblower/_boost_vc/results" >>"/cygdrive/d/iusers/mblower/_boost_vc/results/bjam.log" 2>&1)...
> 
> # Getting test case results out of "/cygdrive/d/iusers/mblower/_boost_vc/results
> 
> /bjam.log"...
> boost_root: D:/iusers\mblower_boost_vc\boost_root
> locate_root: D:/iusers\mblower_boost_vc\boost_root\status\cygdrive\d\iusers\mblower_boost_vc\results
> *****Warning - can't open output file: D:/iusers\mblower_boost_vc\boost_root\status\cygdrive\d\iusers\mblower_boost_vc\results\l-vc14-win-16.0/debug/threading-multi\test_log.xml
> Note: same hybrid file names that Thomas reported
> 
> > <snip>
> 
> I fixed the missing semicolon and confirm that :W isn't working as expected. Does '<' look right? What is that supposed to be?

  $(<) is an alias for $(1) which is the
first argument, i.e. $(targets).

> But still not building the build tools with cl, that might still solve the problem.

  I doubt it.  The b2 command above has a bunch
of /cygdrive paths.

> notice : p is /cygdrive/d/iusers/mblower
> notice : p windows is /cygdrive/d/iusers/mblower

 Is this from the same b2 executable that the test
system is using?  If this is a native windows
build of b2, then this behavior is expected.
If you get this output with a cygwin-built b2,
then something is very wrong.  In this case,
try putting the ECHOs in a separate file to
test b2 without Boost.Build.

test.jam:
p = /cygdrive/d/iusers/mblower ;
ECHO "notice : p is" $p ;
ECHO "notice : p windows is" $(p:W) ;

$ b2 -f test.jam

In Christ,
Steven Watanabe

**Comment by thtrummer** [comment] 2016-02-27 21:33
boost::filesystem treats Cygwin in fact as Windows. It checks if BOOST_WINDOWS_API is defined, which is true for Cygwin:

```
//--------------------------------------------------------------------------------------//

//  Boost.System calls operating system API functions to implement system error category
//  functions. Usually there is no question as to which API is to be used.
//
//  In the case of MinGW or Cygwin/MinGW, however, both POSIX and Windows API's are
//  available. Chaos ensues if other code thinks one is in use when Boost.System was
//  actually built with the other. This header centralizes the API choice and prevents
//  user definition of API macros, thus elminating the possibility of mismatches and the
//  need to test configurations with little or no practical value.
//

//--------------------------------------------------------------------------------------//

#ifndef BOOST_SYSTEM_API_CONFIG_HPP                  
#define BOOST_SYSTEM_API_CONFIG_HPP

# if defined(BOOST_POSIX_API) || defined(BOOST_WINDOWS_API)
#   error user defined BOOST_POSIX_API or BOOST_WINDOWS_API not supported
# endif

//  BOOST_POSIX_API or BOOST_WINDOWS_API specify which API to use
//    Cygwin/MinGW does not predefine _WIN32.
//    Standalone MinGW and all other known Windows compilers do predefine _WIN32
//    Compilers that predefine _WIN32 or __MINGW32__ do so for Windows 64-bit builds too.

# if defined(_WIN32) || defined(__CYGWIN__) // Windows default, including MinGW and Cygwin
#   define BOOST_WINDOWS_API
# else
#   define BOOST_POSIX_API 
# endif

#endif  // BOOST_SYSTEM_API_CONFIG_HPP 
```

**Comment by thtrummer** [comment] 2016-02-28 18:48
The problem seems to be in 'process_jam_log.cpp'.

 The process is spawned with:

```
/cygdrive/e/Boost/Develop/boost_regression/stage/bin/process_jam_log.exe  --locate-root /cygdrive/e/Boost/Develop/results --input-file /cygdrive/e/Boost/Develop/results/bjam.log
```

When parsing the command line, it tries to make the paths absolute:

```
  if ( locate_root.empty() )
  {
    locate_root = boost_root;
  }
  else if ( !locate_root.is_complete() )
  {
    locate_root = ( fs::initial_path() / locate_root ).normalize();
  }
```

Which results in 'locate_root' being "/cygdrive/e/Boost/Develop/results" before and "E:/Boost\Develop\boost_root\status\cygdrive\e\Boost\Develop\results" after the last line of code.

**Comment by swatanabe** [comment] 2016-02-29 17:00
AMDG

On 02/28/2016 11:48 AM, Thomas Trummer wrote:

>   else if ( !locate_root.is_complete() )

What if you replace is_complete with has_root_path?

>   {
>     locate_root = ( fs::initial_path() / locate_root ).normalize();
>   }

In Christ,
Steven Watanabe

**Comment by thtrummer** [comment] 2016-02-29 19:45
> What if you replace is_complete with has_root_path?

Seems to work. I've changed it and started a new run.

**Comment by swatanabe** [comment] 2016-03-01 17:38
AMDG

On 02/29/2016 12:45 PM, Thomas Trummer wrote:

> > What if you replace is_complete with has_root_path?
> > Seems to work. I've changed it and started a new run.

  It looks like your run completed successfully,
so I just committed this fix to process_jam_log.

In Christ,
Steven Watanabe

**Comment by swatanabe** [comment] 2016-03-01 17:57
AMDG

On 02/26/2016 03:28 PM, Melanie Blower wrote:

> I fixed the missing semicolon and confirm that :W isn't working as expected. Does '<' look right? What is that supposed to be?  But still not building the build tools with cl, that might still solve the problem.
> notice : p is /cygdrive/d/iusers/mblower
> notice : p windows is /cygdrive/d/iusers/mblower

There does indeed seem to be a problem with :W

http://www.boost.org/development/tests/develop/developer/output/timber-cygwin-boost-bin-v2-boost-build-tests-gcc-5-3-0-core_language.html

In Christ,
Steven Watanabe

**Comment by swatanabe** [comment] 2016-03-01 18:36
AMDG

On 02/26/2016 03:28 PM, Melanie Blower wrote:

> I fixed the missing semicolon and confirm that :W isn't working as expected.

  I think I finally found the problem.  It should
be fixed in 9da5a06af89ccc2acaef64d07fe22cd43f8cca1b.

In Christ,
Steven Watanabe

**Comment by mibintc** [comment] 2016-03-01 18:39
> I think I finally found the problem. It should
> be fixed in 9da5a06af89ccc2acaef64d07fe22cd43f8cca1b.

Thanks so much, I'll give it a try alter this week. (Would that fix be available in both master and develop?)

**Comment by swatanabe** [comment] 2016-03-01 19:05
AMDG

On 03/01/2016 11:39 AM, Melanie Blower wrote:

> (Would that fix be available in both master and develop?)

  It's only in develop.  I'd like to verify that
it actually works before merging to master.

In Christ,
Steven Watanabe

**Comment by thtrummer** [comment] 2016-03-06 08:52
> It looks like your run completed successfully,
> so I just committed this fix to process_jam_log.

Thanks for your help! I've scratched my local copy and did a full fresh download, which seems to work fine.

**Closed as completed** 2018-10-20 07:43 UTC
